Implementation;Synthesis||(null)||Error: Component(s) 'cpu' needs to be generated before running synthesis||(null);(null)||(null);(null)
Design Entry;SmartDesign Check||(null)||Generation of 'cpu' failed||(null);(null)||(null);(null)
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin address_bus_0:pc_sel||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/address_bus_0:pc_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin address_bus_0:sp_sel||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/address_bus_0:sp_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin address_bus_0:reg_sel[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/address_bus_0:reg_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin alu:op[3:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/alu:op
Design Entry;SmartDesign Check||(null)||Error: control_0 output pins are not being used.  Connect or mark them unused||(null);(null)||Unused Instance;liberoaction://cross_probe/smartdesign/cpu/instances/control_0
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin control_0:latch_opcode_op1||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/control_0:latch_opcode_op1
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin control_0:latch_op2||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/control_0:latch_op2
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin control_0:latch_lsb_imm||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/control_0:latch_lsb_imm
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin control_0:latch_msb_imm||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/control_0:latch_msb_imm
Design Entry;SmartDesign Check||(null)||Warning: Floating output bus pin control_0:control_lines[35:0]||(null);(null)||Floating Driver;liberoaction://cross_probe/smartdesign/cpu/pins/control_0:control_lines
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin lhs:reg_sel[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/lhs:reg_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:reg_sel[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:reg_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:reg_sel_l[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:reg_sel_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:reg_sel_m[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:reg_sel_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:mem_sel||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:mem_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:alu_sel||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:alu_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin main_bus:control_sel||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/main_bus:control_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin memory:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/memory:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin pc:inc||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/pc:inc
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin pc:load||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/pc:load
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_0:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_0:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_0:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_0:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_0:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_0:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_1:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_1:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_1:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_1:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_1:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_1:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_2:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_2:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_2:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_2:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_2:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_2:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_3:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_3:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_3:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_3:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_3:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_3:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_4:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_4:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_4:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_4:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_4:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_4:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_5:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_5:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_5:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_5:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_5:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_5:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_6:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_6:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_6:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_6:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_6:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_6:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_7:we||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_7:we
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_7:we_m||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_7:we_m
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin register_7:we_l||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/register_7:we_l
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin rhs:reg_sel[2:0]||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/rhs:reg_sel
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin sp:inc||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/sp:inc
Design Entry;SmartDesign Check||(null)||Error: Unconnected input pin sp:decr||(null);(null)||Undriven Pin;liberoaction://cross_probe/smartdesign/cpu/pins/sp:decr
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'main_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'alu_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'address_bus.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'control.vhd'||(null);(null)||(null);(null)
